import { systemAdministration, type SystemAgentProvider, type SystemKeychain } from "../../../app/system"

type Form = { alias: string; protocol: string; baseURL: string; keychain: string; apiKey: string; enabled: boolean }
const blank = (): Form => ({ alias: "", protocol: "openai-responses", baseURL: "", keychain: "", apiKey: "", enabled: true })
const optional = (value: string): string | undefined => value.trim() === "" ? undefined : value.trim()
export function createAgentProviderFormController({ onAuthenticationLost, onSystemAccessChange }: { onAuthenticationLost: () => void; onSystemAccessChange: (next: "available" | "denied" | "unavailable") => void }) {
  const state = $state({ provider: null as SystemAgentProvider | null, keychains: [] as SystemKeychain[], form: blank(), error: "", loading: false, saving: false, editing: false })
  async function keychains(): Promise<void> { const response = await systemAdministration("keychains"); if (response.status === 401) { onAuthenticationLost(); return }; if (response.status === 403) { onSystemAccessChange("denied"); return }; if (response.ok) state.keychains = await response.json() as SystemKeychain[] }
  async function load(id: string): Promise<void> {
    state.error = ""; state.loading = true
    try { const response = await systemAdministration(`agent-providers/${encodeURIComponent(id)}`); if (response.status === 401) { onAuthenticationLost(); return }; if (response.status === 403) { onSystemAccessChange("denied"); return }; if (response.status === 404) { state.error = "Agent provider was not found."; return }; if (!response.ok) { state.error = "Agent provider could not be loaded."; return }; state.provider = await response.json() as SystemAgentProvider } catch { state.error = "Agent provider could not be loaded." } finally { state.loading = false }
  }
  async function beginEdit(): Promise<void> { if (state.provider === null) return; state.form = { alias: state.provider.alias, protocol: state.provider.protocol, baseURL: state.provider.base_url ?? "", keychain: state.provider.keychain?.id ?? "", apiKey: "", enabled: state.provider.enabled }; await keychains(); state.editing = true }
  function validate(replacementRequired: boolean): boolean { if (state.form.protocol !== "builtin" && state.form.keychain === "") { state.error = "A keychain is required for this provider."; return false }; if (replacementRequired && state.form.apiKey.trim() === "") { state.error = "An API key is required when changing protocol or keychain."; return false }; return true }
  async function create(): Promise<SystemAgentProvider | null> { state.error = ""; if (!validate(state.form.protocol !== "builtin")) return null; return await save("agent-providers", "POST", state.form) }
  async function update(): Promise<boolean> { if (state.provider === null) return false; state.error = ""; const replacement = state.provider.protocol !== state.form.protocol || state.provider.keychain?.id !== optional(state.form.keychain); if (!validate(replacement)) return false; const saved = await save(`agent-providers/${encodeURIComponent(state.provider.id)}`, "PATCH", state.form, state.provider.revision); if (saved === null) return false; state.provider = saved; state.editing = false; return true }
  async function save(path: string, method: "POST" | "PATCH", form: Form, revision?: number): Promise<SystemAgentProvider | null> { state.saving = true; try { const response = await systemAdministration(path, method, { alias: form.alias, protocol: form.protocol, base_url: optional(form.baseURL), keychain: optional(form.keychain), api_key: optional(form.apiKey), enabled: form.enabled, ...(revision === undefined ? {} : { expected_revision: revision }) }); if (response.status === 401) { onAuthenticationLost(); return null }; if (response.status === 403) { onSystemAccessChange("denied"); return null }; if (response.status === 409) { state.error = "This provider changed elsewhere. The latest settings have been reloaded."; if (state.provider !== null) await load(state.provider.id); return null }; if (!response.ok) { state.error = "Agent provider could not be saved."; return null }; return await response.json() as SystemAgentProvider } catch { state.error = "Agent provider could not be saved."; return null } finally { state.saving = false } }
  return { state, keychains, load, beginEdit, create, update }
}
