#!/usr/bin/env sh

set -eu

SRC_DIR=$DYD_STEM
DEST_DIR=$DYD_BUILD
OS=$(cat "$SRC_DIR/dyd/traits/os")
ARCH=$(cat "$SRC_DIR/dyd/traits/arch")
VERSION=$(cat "$SRC_DIR/dyd/traits/version")
FINGERPRINT=$(cat "$SRC_DIR/dyd/fingerprint")
WORK_DIR="$DEST_DIR/source"

mkdir -p "$DEST_DIR/dyd/commands" "$WORK_DIR/config" "$WORK_DIR/configschema"
cp -R "$SRC_DIR/dyd/assets/." "$WORK_DIR"
chmod -R +w "$WORK_DIR"
cp -R "$SRC_DIR/dyd/dependencies/config-schema-codec/dyd/assets/." "$WORK_DIR/configschema"
cp "$SRC_DIR/dyd/dependencies/config-schema-json/dyd/assets/schema.json" "$WORK_DIR/config/schema.json"

cd "$WORK_DIR"
GOWORK=off go test ./...
GOARCH="$ARCH" GOOS="$OS" GOWORK=off \
	go build -trimpath -buildvcs=false -o "$DEST_DIR/dyd/commands/dyd-stem-run" \
		-ldflags "-X main.Version=$VERSION -X main.Fingerprint=$FINGERPRINT" .
rm -rf "$WORK_DIR"
