#!/usr/bin/env sh

set -eu

SRC_DIR=$DYD_STEM
DEST_DIR=$DYD_BUILD
OS=$(cat "$SRC_DIR/dyd/traits/os")
ARCH=$(cat "$SRC_DIR/dyd/traits/arch")
VERSION=$(cat "$SRC_DIR/dyd/traits/version")
FINGERPRINT=$(cat "$SRC_DIR/dyd/fingerprint")

mkdir -p "$DEST_DIR/dyd/commands"

cd "$SRC_DIR/dyd/assets"
GOARCH="$ARCH" GOOS="$OS" GOWORK=off \
	go build -trimpath -buildvcs=false -o "$DEST_DIR/dyd/commands/dyd-stem-run" \
		-ldflags "-X main.Version=$VERSION -X main.Fingerprint=$FINGERPRINT" .
