{{- $config := .Values.config -}}
{{- if hasPrefix "base64:" $config -}}
{{- $config = trimPrefix "base64:" $config | b64dec -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gatehouse.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatehouse.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ $config | indent 4 }}
