{{- if .Values.env -}}
{{- $env := dict -}}
{{- range .Values.env -}}
{{- if hasKey $env .name -}}
{{- fail (printf "env contains duplicate name %q" .name) -}}
{{- end -}}
{{- $_ := set $env .name .value -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gatehouse.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatehouse.labels" . | nindent 4 }}
stringData:
  {{- toYaml $env | nindent 2 }}
{{- end -}}
