import type { Route } from "./route"

export type RouteOwner =
  | "project-dashboard"
  | "project-files"
  | "project-notes"
  | "project-tasks"
  | "project-secrets"
  | "project-records"
  | "session-chat"
  | "session-files"
  | "session-notes"
  | "session-tasks"
  | "session-secrets"
  | "chat-collection"
  | "project-collection"
  | "groups"
  | "system-overview"
  | "system-grants"
  | "principals"
  | "agent-provider-list"
  | "agent-provider-new"
  | "agent-provider-detail"
  | "agent-model-list"
  | "agent-model-new"
  | "agent-model-detail"
  | "storage-provider-list"
  | "storage-provider-new"
  | "storage-provider-detail"
  | "workspace-agent-binding-list"
  | "workspace-agent-binding-new"
  | "workspace-agent-binding-detail"
  | "workspace-storage-binding-list"
  | "workspace-storage-binding-new"
  | "workspace-storage-binding-detail"
  | "workspace-dashboard"
  | "access"

function unhandledRoute(route: never): never {
  throw new Error(`Unhandled route ${JSON.stringify(route)}`)
}

export function routeOwner(route: Route): RouteOwner {
  switch (route.kind) {
    case "project":
      return "project-dashboard"
    case "project-files":
    case "project-file":
      return "project-files"
    case "project-notes":
    case "project-note-new":
    case "project-note":
      return "project-notes"
    case "project-tasks":
    case "project-task-new":
    case "project-task":
      return "project-tasks"
    case "project-secrets":
    case "project-secret-new":
    case "project-secret":
      return "project-secrets"
    case "project-records":
    case "project-record-schema-new":
    case "project-record-schema":
    case "project-record-schema-edit":
    case "project-record-new":
    case "project-record":
    case "project-record-edit":
      return "project-records"
    case "session-chat":
      return "session-chat"
    case "session-files":
      return "session-files"
    case "session-notes":
    case "session-note-new":
    case "session-note":
    case "session-note-edit":
    case "session-note-revision":
      return "session-notes"
    case "session-tasks":
    case "session-task-new":
    case "session-task":
      return "session-tasks"
    case "session-secrets":
    case "session-secret-new":
    case "session-secret":
      return "session-secrets"
    case "session-collection":
      return "chat-collection"
    case "project-collection":
      return "project-collection"
    case "group-collection":
      return "groups"
    case "system":
      return "system-overview"
    case "system-grants":
      return "system-grants"
    case "system-principals":
      return "principals"
    case "system-agent-providers":
      return "agent-provider-list"
    case "system-agent-provider-new":
      return "agent-provider-new"
    case "system-agent-provider":
      return "agent-provider-detail"
    case "system-agent-models":
      return "agent-model-list"
    case "system-agent-model-new":
      return "agent-model-new"
    case "system-agent-model":
      return "agent-model-detail"
    case "system-storage-providers":
      return "storage-provider-list"
    case "system-storage-provider-new":
      return "storage-provider-new"
    case "system-storage-provider":
      return "storage-provider-detail"
    case "system-workspace-agent-bindings":
      return "workspace-agent-binding-list"
    case "system-workspace-agent-binding-new":
      return "workspace-agent-binding-new"
    case "system-workspace-agent-binding":
      return "workspace-agent-binding-detail"
    case "system-workspace-storage-bindings":
      return "workspace-storage-binding-list"
    case "system-workspace-storage-binding-new":
      return "workspace-storage-binding-new"
    case "system-workspace-storage-binding":
      return "workspace-storage-binding-detail"
    case "app-home":
    case "workspace":
    case "not-found":
      return "workspace-dashboard"
    case "login":
    case "no-access":
      return "access"
  }
  return unhandledRoute(route)
}
