#!/usr/bin/env sh

set -eu

SRC_DIR=$DYD_STEM
DEST_DIR=$DYD_BUILD

mkdir -p "$DEST_DIR/dyd/assets" "$DEST_DIR/dyd/commands" "$DEST_DIR/dyd/dependencies" "$DEST_DIR/dyd/traits"
cp "$SRC_DIR/dyd/dependencies/release-artifacts/dyd/traits/version" "$DEST_DIR/dyd/traits/version"
if [ -d "$SRC_DIR/dyd/assets" ]; then
	cp -R "$SRC_DIR/dyd/assets/." "$DEST_DIR/dyd/assets"
fi
cp "$SRC_DIR/dyd/commands/dyd-stem-run" "$DEST_DIR/dyd/commands/dyd-stem-run"
for dependency in "$SRC_DIR"/dyd/dependencies/*; do
	ln -s "$dependency" "$DEST_DIR/dyd/dependencies/${dependency##*/}"
done
