name: gatehouse-local-dev

services:
  gatehouse:
    image: ${GATEHOUSE_IMAGE}
    ports:
      - "4283:4283"
    environment:
      - GATEHOUSE_CONFIG
      - GATEHOUSE_DIAG
      - GATEHOUSE_KEYCHAIN=local-development-keychain
      - GATEHOUSE_ROOT_PASSWORD=password-root
      - OPENAI_API_KEY
      - LOCAL_DEV_S3_ACCESS_KEY_ID=local-development-s3
      - LOCAL_DEV_S3_SECRET_ACCESS_KEY=local-development-s3-secret
