name: gatehouse-local-dev

services:
  gatehouse:
    image: ${GATEHOUSE_IMAGE}
    ports:
      - "4283:4283"
    environment:
      - GATEHOUSE_CONFIG
      - GATEHOUSE_KEYCHAIN=local-development-keychain
      - GATEHOUSE_ROOT_PASSWORD=password-root
      - OPENAI_API_KEY
