package httpservice

import (
	"context"
	"crypto/rand"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"gatehouse/auth"
	"gatehouse/authz"
	"gatehouse/database"
	"gatehouse/keychain"
	"gatehouse/model"
)

type systemProviderRequest struct { Alias string `json:"alias"`; Protocol string `json:"protocol"`; BaseURL *string `json:"base_url"`; Keychain *string `json:"keychain"`; APIKey *string `json:"api_key"`; Enabled bool `json:"enabled"`; ExpectedRevision *int `json:"expected_revision"` }
type systemModelRequest struct { Alias string `json:"alias"`; Provider string `json:"provider"`; Model string `json:"model"`; Parameters string `json:"parameters"`; Compaction string `json:"compaction"`; MaxTurns int `json:"max_turns"`; MaxOutputTokens int `json:"max_output_tokens"`; Enabled bool `json:"enabled"`; ExpectedRevision *int `json:"expected_revision"` }
type systemStorageRequest struct { Alias string `json:"alias"`; Protocol string `json:"protocol"`; Endpoint *string `json:"endpoint"`; Region *string `json:"region"`; Bucket *string `json:"bucket"`; AccessKeyID *string `json:"access_key_id"`; Keychain *string `json:"keychain"`; SecretAccessKey *string `json:"secret_access_key"`; Enabled bool `json:"enabled"`; ExpectedRevision *int `json:"expected_revision"` }
type systemWorkspaceAgentRequest struct { Priority int `json:"priority"`; Label *string `json:"label"`; SystemPrompt *string `json:"system_prompt"`; Enabled bool `json:"enabled"`; ExpectedRevision *int `json:"expected_revision"` }
type systemWorkspaceStorageRequest struct { Priority int `json:"priority"`; Enabled bool `json:"enabled"`; ExpectedRevision *int `json:"expected_revision"` }

func systemKeychains(keyring *keychain.Keyring, store *database.Store, tokens *auth.BearerTokens) http.HandlerFunc { return func(w http.ResponseWriter, r *http.Request) { if !systemManage(w,r,store,tokens) { return }; if r.Method != http.MethodGet { w.WriteHeader(http.StatusMethodNotAllowed); return }; if keyring == nil { http.Error(w,"keychain administration unavailable",http.StatusServiceUnavailable); return }; err, refs := keyring.Current(r.Context()); if err != nil { http.Error(w,"internal server error",500); return }; writeJSON(w,refs) } }

func systemAgentProviders(store *database.Store, ring *keychain.Keyring, tokens *auth.BearerTokens) http.HandlerFunc { return func(w http.ResponseWriter, r *http.Request) { if !systemManage(w,r,store,tokens) { return }; if r.Method == http.MethodGet { err,v:=store.SystemAgentProvidersGet(r.Context()); adminResult(w,err,v); return }; if r.Method != http.MethodPost { w.WriteHeader(405); return }; var q systemProviderRequest; if !adminDecode(w,r,&q) { return }; input,err:=agentProviderInput(r.Context(),ring,q); if err != nil { adminError(w,err); return }; err,v:=store.SystemAgentProviderCreate(r.Context(),input); adminResult(w,err,v) } }
func systemAgentProvider(store *database.Store, ring *keychain.Keyring, tokens *auth.BearerTokens) http.HandlerFunc { return func(w http.ResponseWriter, r *http.Request) { if !systemManage(w,r,store,tokens) { return }; id:=r.PathValue("provider"); if r.Method == http.MethodGet { err,v:=store.SystemAgentProviderGet(r.Context(),id); if err!=nil { adminError(w,err); return }; if v==nil { http.NotFound(w,r); return }; writeJSON(w,v); return }; if r.Method != http.MethodPatch { w.WriteHeader(405); return }; var q systemProviderRequest; if !adminDecode(w,r,&q)||q.ExpectedRevision==nil { if q.ExpectedRevision==nil { http.Error(w,"expected revision is required",400) }; return }; input,err:=agentProviderInput(r.Context(),ring,q); if err!=nil { adminError(w,err); return }; err,v:=store.SystemAgentProviderUpdate(r.Context(),id,*q.ExpectedRevision,input); adminResult(w,err,v) } }

func systemAgentModels(store *database.Store, tokens *auth.BearerTokens) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request) { if !systemManage(w,r,store,tokens) { return }; if r.Method==http.MethodGet { err,v:=store.SystemAgentModelsGet(r.Context()); adminResult(w,err,v); return }; if r.Method!=http.MethodPost { w.WriteHeader(405); return }; var q systemModelRequest; if !adminDecode(w,r,&q) { return }; err,v:=store.SystemAgentModelCreate(r.Context(),agentModelInput(q)); adminResult(w,err,v) } }
func systemAgentModel(store *database.Store,tokens *auth.BearerTokens) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request) { if !systemManage(w,r,store,tokens) { return }; id:=r.PathValue("model"); if r.Method==http.MethodGet { err,v:=store.SystemAgentModelGet(r.Context(),id); if err!=nil { adminError(w,err); return }; if v==nil { http.NotFound(w,r); return }; writeJSON(w,v); return }; if r.Method!=http.MethodPatch { w.WriteHeader(405); return }; var q systemModelRequest; if !adminDecode(w,r,&q)||q.ExpectedRevision==nil { if q.ExpectedRevision==nil { http.Error(w,"expected revision is required",400) }; return }; err,v:=store.SystemAgentModelUpdate(r.Context(),id,*q.ExpectedRevision,agentModelInput(q)); adminResult(w,err,v) } }

func systemStorageProviders(store *database.Store,ring *keychain.Keyring,tokens *auth.BearerTokens) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request) { if !systemManage(w,r,store,tokens) { return }; if r.Method==http.MethodGet { err,v:=store.SystemStorageProvidersGet(r.Context()); adminResult(w,err,v); return }; if r.Method!=http.MethodPost { w.WriteHeader(405); return }; var q systemStorageRequest; if !adminDecode(w,r,&q) { return }; input,err:=storageProviderInput(r.Context(),ring,q); if err!=nil { adminError(w,err); return }; err,v:=store.SystemStorageProviderCreate(r.Context(),input); adminResult(w,err,v) } }
func systemStorageProvider(store *database.Store,ring *keychain.Keyring,tokens *auth.BearerTokens) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request) { if !systemManage(w,r,store,tokens) { return }; id:=r.PathValue("provider"); if r.Method==http.MethodGet { err,v:=store.SystemStorageProviderGet(r.Context(),id); if err!=nil { adminError(w,err); return }; if v==nil { http.NotFound(w,r); return }; writeJSON(w,v); return }; if r.Method!=http.MethodPatch { w.WriteHeader(405); return }; var q systemStorageRequest; if !adminDecode(w,r,&q)||q.ExpectedRevision==nil { if q.ExpectedRevision==nil { http.Error(w,"expected revision is required",400) }; return }; input,err:=storageProviderInput(r.Context(),ring,q); if err!=nil { adminError(w,err); return }; err,v:=store.SystemStorageProviderUpdate(r.Context(),id,*q.ExpectedRevision,input); adminResult(w,err,v) } }

func systemWorkspaceAgents(store *database.Store,tokens *auth.BearerTokens) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request) { if !systemManage(w,r,store,tokens) { return }; if r.Method==http.MethodGet { err,v:=store.SystemWorkspaceAgentsGet(r.Context()); adminResult(w,err,v); return }; w.WriteHeader(405) } }
func systemWorkspaceAgent(store *database.Store,tokens *auth.BearerTokens) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request) { if !systemManage(w,r,store,tokens) { return }; workspace,modelID:=r.PathValue("workspace"),r.PathValue("model"); if r.Method==http.MethodGet { err,v:=store.SystemWorkspaceAgentGet(r.Context(),workspace,modelID); if err!=nil { adminError(w,err); return }; if v==nil { http.NotFound(w,r); return }; writeJSON(w,v); return }; var q systemWorkspaceAgentRequest; if !adminDecode(w,r,&q) { return }; input:=database.SystemWorkspaceAgentInput{Priority:q.Priority,Label:q.Label,SystemPrompt:q.SystemPrompt,Enabled:q.Enabled}; if r.Method==http.MethodPost { err,v:=store.SystemWorkspaceAgentCreate(r.Context(),workspace,modelID,input); adminResult(w,err,v); return }; if r.Method==http.MethodPatch&&q.ExpectedRevision!=nil { err,v:=store.SystemWorkspaceAgentUpdate(r.Context(),workspace,modelID,*q.ExpectedRevision,input); adminResult(w,err,v); return }; http.Error(w,"expected revision is required",400) } }

func systemWorkspaceStorageProviders(store *database.Store,tokens *auth.BearerTokens) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request) { if !systemManage(w,r,store,tokens) { return }; if r.Method==http.MethodGet { err,v:=store.SystemWorkspaceStorageProvidersGet(r.Context()); adminResult(w,err,v); return }; w.WriteHeader(405) } }
func systemWorkspaceStorageProvider(store *database.Store,tokens *auth.BearerTokens) http.HandlerFunc { return func(w http.ResponseWriter,r *http.Request) { if !systemManage(w,r,store,tokens) { return }; workspace,provider:=r.PathValue("workspace"),r.PathValue("provider"); if r.Method==http.MethodGet { err,v:=store.SystemWorkspaceStorageProviderGet(r.Context(),workspace,provider); if err!=nil { adminError(w,err); return }; if v==nil { http.NotFound(w,r); return }; writeJSON(w,v); return }; var q systemWorkspaceStorageRequest; if !adminDecode(w,r,&q) { return }; input:=database.SystemWorkspaceStorageProviderInput{Priority:q.Priority,Enabled:q.Enabled}; if r.Method==http.MethodPost { err,v:=store.SystemWorkspaceStorageProviderCreate(r.Context(),workspace,provider,input); adminResult(w,err,v); return }; if r.Method==http.MethodPatch&&q.ExpectedRevision!=nil { err,v:=store.SystemWorkspaceStorageProviderUpdate(r.Context(),workspace,provider,*q.ExpectedRevision,input); adminResult(w,err,v); return }; http.Error(w,"expected revision is required",400) } }

func systemManage(w http.ResponseWriter,r *http.Request,store *database.Store,tokens *auth.BearerTokens) bool { claims,ok:=authenticate(w,r,tokens); return ok&&systemActionAllowed(w,r,store,claims,authz.SystemManage) }
func adminDecode(w http.ResponseWriter,r *http.Request,target any) bool { d:=json.NewDecoder(http.MaxBytesReader(w,r.Body,1<<20)); d.DisallowUnknownFields(); if d.Decode(target)!=nil { http.Error(w,"invalid system administration request",400); return false }; return true }
func adminResult(w http.ResponseWriter,err error,value any) { if err!=nil { adminError(w,err); return }; if value==nil { w.WriteHeader(http.StatusNotFound); return }; writeJSON(w,value) }
func adminError(w http.ResponseWriter,err error) { if errors.Is(err,database.ErrRevisionConflict)||errors.Is(err,database.ErrAgentProviderExists)||errors.Is(err,database.ErrAgentModelExists)||errors.Is(err,database.ErrStorageProviderExists)||errors.Is(err,database.ErrWorkspaceAgentExists)||errors.Is(err,database.ErrWorkspaceStorageProviderExists) { http.Error(w,err.Error(),409); return }; if errors.Is(err,database.ErrAdminDependencyMissing) { http.Error(w,err.Error(),404); return }; http.Error(w,err.Error(),400) }
func agentModelInput(q systemModelRequest) database.SystemAgentModelInput { return database.SystemAgentModelInput{Alias:q.Alias,ProviderID:q.Provider,Model:q.Model,Parameters:q.Parameters,Compaction:q.Compaction,MaxTurns:q.MaxTurns,MaxOutputTokens:q.MaxOutputTokens,Enabled:q.Enabled} }
func agentProviderInput(ctx context.Context,ring *keychain.Keyring,q systemProviderRequest) (database.SystemAgentProviderInput,error) { key,err:=systemCredential(ctx,ring,q.Keychain,q.APIKey,"gh=v1|agent-provider|alias="+q.Alias); if err!=nil{return database.SystemAgentProviderInput{},err}; return database.SystemAgentProviderInput{Alias:q.Alias,Protocol:q.Protocol,BaseURL:q.BaseURL,Keychain:key.ref,EncryptedAPIKey:credentialText(key),Enabled:q.Enabled},nil }
func storageProviderInput(ctx context.Context,ring *keychain.Keyring,q systemStorageRequest) (database.SystemStorageProviderInput,error) { key,err:=systemCredential(ctx,ring,q.Keychain,q.SecretAccessKey,"gh=v1|storage-provider|alias="+q.Alias); if err!=nil{return database.SystemStorageProviderInput{},err}; return database.SystemStorageProviderInput{Alias:q.Alias,Protocol:q.Protocol,Endpoint:q.Endpoint,Region:q.Region,Bucket:q.Bucket,AccessKeyID:q.AccessKeyID,Keychain:key.ref,EncryptedSecretAccessKey:key.text,Enabled:q.Enabled},nil }
type sealedCredential struct { ref *model.KeychainRef; text *string }
func credentialText(value sealedCredential) *string { return value.text }
func systemCredential(ctx context.Context,ring *keychain.Keyring,id *string,plain *string,aad string) (sealedCredential,error) { if id==nil { if plain!=nil { return sealedCredential{},fmt.Errorf("keychain is required") }; return sealedCredential{},nil }; if ring==nil { return sealedCredential{},fmt.Errorf("keychain administration unavailable") }; err,refs:=ring.Current(ctx); if err!=nil{return sealedCredential{},err}; var ref *model.KeychainRef; for _,candidate:=range refs { if candidate.Id==*id { copy:=candidate; ref=&copy; break } }; if ref==nil{return sealedCredential{},fmt.Errorf("configured keychain not found")}; if plain==nil{return sealedCredential{ref:ref},nil}; keysErr,keys:=ring.Get(ctx,[]model.KeychainRef{*ref}); if keysErr!=nil{return sealedCredential{},keysErr}; defer clear(keys[*ref]); encryptedErr,encrypted:=keychain.Seal(rand.Reader,keys[*ref],[]byte(aad),[]byte(*plain)); if encryptedErr!=nil{return sealedCredential{},encryptedErr}; encrypted.AAD=keychain.AADAlias; text:=encrypted.String(); return sealedCredential{ref:ref,text:&text},nil }
