#!/usr/bin/env sh

set -eu

SRC_DIR=$DYD_STEM
DEST_DIR=$DYD_BUILD
OS=$(cat "$SRC_DIR/dyd/traits/os")
ARCH=$(cat "$SRC_DIR/dyd/traits/arch")
VERSION=$(cat "$SRC_DIR/dyd/traits/version")
FINGERPRINT=$(cat "$SRC_DIR/dyd/fingerprint")
WORK_DIR="$DEST_DIR/source"

mkdir -p "$DEST_DIR/dyd/commands" "$DEST_DIR/dyd/traits" "$WORK_DIR/config" "$WORK_DIR/configschema" "$WORK_DIR/apischema" "$WORK_DIR/httpservice/web" "$WORK_DIR/model"
cp "$SRC_DIR/dyd/traits/version" "$DEST_DIR/dyd/traits/version"
cp -R "$SRC_DIR/dyd/assets/." "$WORK_DIR"
chmod -R +w "$WORK_DIR"
cp -R "$SRC_DIR/dyd/dependencies/config-schema-codec/dyd/assets/." "$WORK_DIR/configschema"
cp -R "$SRC_DIR/dyd/dependencies/api-schema-codec/dyd/assets/." "$WORK_DIR/apischema"
cp "$SRC_DIR/dyd/dependencies/config-schema-json/dyd/assets/schema.json" "$WORK_DIR/config/schema.json"
cp -R "$SRC_DIR/dyd/dependencies/model-schema/dyd/assets/." "$WORK_DIR/model"
cp -R "$SRC_DIR/dyd/dependencies/web/dyd/assets/." "$WORK_DIR/httpservice/web"
mkdir -p "$WORK_DIR/httpservice/web/tools/session-file-picker"
cp -R "$SRC_DIR/dyd/dependencies/web-session-file-picker/dyd/assets/." "$WORK_DIR/httpservice/web/tools/session-file-picker"
chmod -R u+w "$WORK_DIR/httpservice/web"

cd "$WORK_DIR"
GOARCH="$ARCH" GOOS="$OS" GOWORK=off \
	go build -trimpath -buildvcs=false -o "$DEST_DIR/dyd/commands/dyd-stem-run" \
		-ldflags "-X main.Version=$VERSION -X main.Fingerprint=$FINGERPRINT" .
rm -rf "$WORK_DIR"