#!/usr/bin/env bash

set -euf -o pipefail

assert_contains() {
    case "$1" in
        *"$2"*) ;;
        *)
            printf '%s\n' "[ERROR] Fail: $3 does not contain $2" >&2
            return 1
            ;;
    esac
}

version_output=$(gatehouse version)
assert_contains "$version_output" "version=0.1.0" "version output"
assert_contains "$version_output" "source_fingerprint=v2-" "version output"
assert_contains "$version_output" "arch=" "version output"
assert_contains "$version_output" "os=" "version output"
