#!/usr/bin/env sh

set -eu

SRC_DIR=$DYD_STEM
DEST_DIR=$DYD_BUILD

mkdir -p "$DEST_DIR/dyd/assets" "$DEST_DIR/dyd/traits"
cp "$SRC_DIR/dyd/dependencies/gatehouse-linux-amd64/dyd/traits/version" "$DEST_DIR/dyd/traits/version"
for dependency in "$SRC_DIR"/dyd/dependencies/gatehouse-*; do
	name=${dependency##*/}
	cp "$dependency/dyd/commands/dyd-stem-run" "$DEST_DIR/dyd/assets/$name"
done
cp -R "$SRC_DIR/dyd/dependencies/image-gatehouse/dyd/assets" "$DEST_DIR/dyd/assets/image-gatehouse"
